## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [ ]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2023-01-17 01:39:27--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.04s   

2023-01-17 01:39:28 (29.0 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [12]:
# read it in to inspect it
with open("C:\\Users\\ncbir\\Desktop\\seqsmile.txt", 'r', encoding='utf-8') as f:
    text = f.read()

In [13]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  77762536


In [14]:
# let's look at the first 1000 characters
print(text[:1000])

MLLETQDALYVALELVIAALSVAGNVLVCAAVGTANTLQTPTNYFLVSLAAADVAVGLFAIPFAITISLGFCTDFYGCLFLACFVLVLTQSSIFSLLAVAVDRYLAICVPLRYKSLVTGTRARGVIAVLWVLAFGIGLTPFLGWNSKDSATNNCTEPWDGTTNESCCLVKCLFENVVPMSYMVYFNFFGCVLPPLLIMLVIYIKIFLVACRQLQRTELMDHSRTTLQREIHAAKSLAMIVGIFALCWLPVHAVNCVTLFQPAQGKNKPKWAMNMAILLSHANSVVNPIVYAYRNRDFRYTFHKIISRYLLCQADVKSGNGQAGVQPALGVGL COc1ccc(NC(=O)Nc2nc3ccc(Cl)cc3c3nc(nn23)-c2ccco2)cc1
MKSILDGLADTTFRTITTDLLYVGSNDIQYEDIKGDMASKLGYFPQKFPLTSFRGSPFQEKMTAGDNSPLVPAGDTTNITEFYNKSLSSFKENEDNIQCGENFMDMECFMILNPSQQLAIAVLSLTLGTFTVLENLLVLCVILHSRSLRCRPSYHFIGSLAVADLLGSVIFVYSFVDFHVFHRKDSPNVFLFKLGGVTASFTASVGSLFLTAIDRYISIHRPLAYKRIVTRPKAVVAFCLMWTIAIVIAVLPLLGWNCKKLQSVCSDIFPLIDETYLMFWIGVTSVLLLFIVYAYMYILWKAHSHAVRMIQRGTQKSIIIHTSEDGKVQVTRPDQARMDIRLAKTLVLILVVLIICWGPLLAIMVYDVFGKMNKLIKTVFAFCSMLCLLNSTVNPIIYALRSKDLRHAFRSMFPSCEGTAQPLDNSMGDSDCLHKHANNTASMHRAAESCIKSTVKIAKVTMSVSTDTSAEAL Cc1ccc2c(c1)oc1c(nn(-c3ccc(Cl)cc3Cl)c21)C(=O)N[C@H]1C2(C)CCC(C2)C1(C)C
MANSASPEQNQNHCSAINNSIPLMQGNLPTLTLSGKIRVTVTFFLFLLSATFNASFLLKLQKWTQKKEK

In [15]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 #()+-./123456789=@ABCDEFGHIKLMNOPQRSTUVWXYZ[\]abcdefghiklmnopqrstuvwy
71


In [16]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("COc1ccc(NC(=O)N"))
print(decode(encode("COc1ccc(NC(=O)N")))

[22, 33, 50, 9, 50, 50, 50, 3, 32, 22, 3, 18, 33, 4, 32]
COc1ccc(NC(=O)N


In [11]:
stoi

{'\n': 0,
 ' ': 1,
 '#': 2,
 '(': 3,
 ')': 4,
 '+': 5,
 '-': 6,
 '.': 7,
 '/': 8,
 '1': 9,
 '2': 10,
 '3': 11,
 '4': 12,
 '5': 13,
 '6': 14,
 '7': 15,
 '8': 16,
 '9': 17,
 '=': 18,
 '@': 19,
 'A': 20,
 'B': 21,
 'C': 22,
 'D': 23,
 'E': 24,
 'F': 25,
 'G': 26,
 'H': 27,
 'I': 28,
 'K': 29,
 'L': 30,
 'M': 31,
 'N': 32,
 'O': 33,
 'P': 34,
 'Q': 35,
 'R': 36,
 'S': 37,
 'T': 38,
 'U': 39,
 'V': 40,
 'W': 41,
 'X': 42,
 'Y': 43,
 'Z': 44,
 '[': 45,
 '\\': 46,
 ']': 47,
 'a': 48,
 'b': 49,
 'c': 50,
 'd': 51,
 'e': 52,
 'f': 53,
 'g': 54,
 'h': 55,
 'i': 56,
 'k': 57,
 'l': 58,
 'm': 59,
 'n': 60,
 'o': 61,
 'p': 62,
 'q': 63,
 'r': 64,
 's': 65,
 't': 66,
 'u': 67,
 'v': 68,
 'w': 69,
 'y': 70}

In [6]:
file_path = "C:\\Users\\ncbir\\Desktop\\dencode1.txt"

# Otwarcie pliku w trybie zapisu
with open(file_path, 'w') as file:
    # Iteracja przez elementy słownika i zapisanie ich do pliku
    for key, value in itos.items():
        file.write(f"{key}: {value}\n")

In [17]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text[:10000000]), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([10000000]) torch.int64
tensor([31, 30, 30, 24, 38, 35, 23, 20, 30, 43, 40, 20, 30, 24, 30, 40, 28, 20,
        20, 30, 37, 40, 20, 26, 32, 40, 30, 40, 22, 20, 20, 40, 26, 38, 20, 32,
        38, 30, 35, 38, 34, 38, 32, 43, 25, 30, 40, 37, 30, 20, 20, 20, 23, 40,
        20, 40, 26, 30, 25, 20, 28, 34, 25, 20, 28, 38, 28, 37, 30, 26, 25, 22,
        38, 23, 25, 43, 26, 22, 30, 25, 30, 20, 22, 25, 40, 30, 40, 30, 38, 35,
        37, 37, 28, 25, 37, 30, 30, 20, 40, 20, 40, 23, 36, 43, 30, 20, 28, 22,
        40, 34, 30, 36, 43, 29, 37, 30, 40, 38, 26, 38, 36, 20, 36, 26, 40, 28,
        20, 40, 30, 41, 40, 30, 20, 25, 26, 28, 26, 30, 38, 34, 25, 30, 26, 41,
        32, 37, 29, 23, 37, 20, 38, 32, 32, 22, 38, 24, 34, 41, 23, 26, 38, 38,
        32, 24, 37, 22, 22, 30, 40, 29, 22, 30, 25, 24, 32, 40, 40, 34, 31, 37,
        43, 31, 40, 43, 25, 32, 25, 25, 26, 22, 40, 30, 34, 34, 30, 30, 28, 31,
        30, 40, 28, 43, 28, 29, 28, 25, 30, 40, 20, 22, 36, 35, 30, 35, 36, 38,
     

In [8]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [9]:
block_size = 8
train_data[:block_size+1]

tensor([31, 30, 30, 24, 38, 35, 23, 20, 30])

In [10]:
train_data[2]

tensor(30)

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([31]) the target: 30
when input is tensor([31, 30]) the target: 30
when input is tensor([31, 30, 30]) the target: 24
when input is tensor([31, 30, 30, 24]) the target: 38
when input is tensor([31, 30, 30, 24, 38]) the target: 35
when input is tensor([31, 30, 30, 24, 38, 35]) the target: 23
when input is tensor([31, 30, 30, 24, 38, 35, 23]) the target: 20
when input is tensor([31, 30, 30, 24, 38, 35, 23, 20]) the target: 30


In [12]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[38, 37, 25, 30, 37, 30, 40, 32],
        [43, 32, 25, 30, 37, 26, 29, 25],
        [43, 36, 25, 40, 38, 34, 26, 24],
        [40, 35, 34, 28, 26, 34, 35, 38]])
targets:
torch.Size([4, 8])
tensor([[37, 25, 30, 37, 30, 40, 32, 20],
        [32, 25, 30, 37, 26, 29, 25, 36],
        [36, 25, 40, 38, 34, 26, 24, 36],
        [35, 34, 28, 26, 34, 35, 38, 34]])
----
when input is [38] the target: 37
when input is [38, 37] the target: 25
when input is [38, 37, 25] the target: 30
when input is [38, 37, 25, 30] the target: 37
when input is [38, 37, 25, 30, 37] the target: 30
when input is [38, 37, 25, 30, 37, 30] the target: 40
when input is [38, 37, 25, 30, 37, 30, 40] the target: 32
when input is [38, 37, 25, 30, 37, 30, 40, 32] the target: 20
when input is [43] the target: 32
when input is [43, 32] the target: 25
when input is [43, 32, 25] the target: 30
when input is [43, 32, 25, 30] the target: 37
when input is [43, 32, 25, 30, 37] the target: 26
when inp

In [13]:
print(xb) # our input to the transformer

tensor([[38, 37, 25, 30, 37, 30, 40, 32],
        [43, 32, 25, 30, 37, 26, 29, 25],
        [43, 36, 25, 40, 38, 34, 26, 24],
        [40, 35, 34, 28, 26, 34, 35, 38]])


In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 71])
tensor(4.7214, grad_fn=<NllLossBackward0>)

-r]Wwkf8TC)UuUbEkmTY8+Y7/aR@E oCB.Q7ba1HZl3lsGZ@si/aX/w8y//Q=95Q74lTsuI6mVr]1GZl3uUb.fLb5k+O=a/kC@i7


In [15]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [16]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.6472978591918945


In [17]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


gq8SLW]w8yrp
MswvTgb5vC#.UA[AbPep.[MNilf 49ae@cIhSR9TTT
Cgd(eqeWKCYSB.[2 72K6B2HPaeLnnOOvl@B3Lm-lIF\DmV 1tGvUfTE22LMNDUZOmqZGbSGS
s7ES/w#Bk+1y/lPew44GS#t54Q[Ni=nSGS/NQeQou6u\\K3DS9N
cCp\\KT=Qa#]Vlw=oY1AEivrLRS
pQ9D.gRrs47yhUV1G)#YHZh=2QdouiXqcbP2Z=FCBdV\\K2S7wu@rkqkCr]LI /Qe
lylH[9+1fn(gb#iyvwdp.3nOm72hh
 laGB.(hQEewP- 1G5w.pVfSG7PlRsN#YUSbX3.31whZb46/
=TZwv]\\VANEG47vwr]XPab(+P.oUT@\Z.@LlRYprMM1v
ymSw8+tT1dpDuRccS2CFAcCYKCLWpr]8/Mivf-34NNZG6K6F)p4K8@lHrcNu
aHP4tKo[O]Zh9sv/wD.v7Sr8-ES91GAO p.()w


## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


True

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 100000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open("C:\\Users\\ncbir\\Desktop\\seqsmile.txt", 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=1000)[0].tolist()))


0.210503 M parameters
step 0: train loss 4.4041, val loss 4.4016
step 100: train loss 2.9087, val loss 2.9048
step 200: train loss 2.8039, val loss 2.8013
step 300: train loss 2.7746, val loss 2.7504
step 400: train loss 2.7381, val loss 2.7471
step 500: train loss 2.7265, val loss 2.7373
step 600: train loss 2.7100, val loss 2.7062
step 700: train loss 2.7164, val loss 2.7027
step 800: train loss 2.7103, val loss 2.7016
step 900: train loss 2.6927, val loss 2.6813
step 1000: train loss 2.6951, val loss 2.6824
step 1100: train loss 2.6733, val loss 2.6682
step 1200: train loss 2.6790, val loss 2.6766
step 1300: train loss 2.6572, val loss 2.6648
step 1400: train loss 2.6519, val loss 2.6580
step 1500: train loss 2.6468, val loss 2.6335
step 1600: train loss 2.6555, val loss 2.6294
step 1700: train loss 2.6276, val loss 2.6387
step 1800: train loss 2.6360, val loss 2.6174
step 1900: train loss 2.6206, val loss 2.6125
step 2000: train loss 2.6119, val loss 2.6051
step 2100: train loss 2.

step 17700: train loss 1.6762, val loss 1.6695
step 17800: train loss 1.7009, val loss 1.6900
step 17900: train loss 1.6693, val loss 1.7130
step 18000: train loss 1.6750, val loss 1.6770
step 18100: train loss 1.6304, val loss 1.6380
step 18200: train loss 1.7047, val loss 1.6595
step 18300: train loss 1.6872, val loss 1.6875
step 18400: train loss 1.6616, val loss 1.6575
step 18500: train loss 1.6847, val loss 1.6670
step 18600: train loss 1.6446, val loss 1.6336
step 18700: train loss 1.7310, val loss 1.6696
step 18800: train loss 1.6649, val loss 1.6601
step 18900: train loss 1.6795, val loss 1.6467
step 19000: train loss 1.6669, val loss 1.6615
step 19100: train loss 1.6519, val loss 1.6334
step 19200: train loss 1.6407, val loss 1.6962
step 19300: train loss 1.6619, val loss 1.6479
step 19400: train loss 1.6993, val loss 1.6685
step 19500: train loss 1.6254, val loss 1.6489
step 19600: train loss 1.6742, val loss 1.6483
step 19700: train loss 1.6640, val loss 1.6600
step 19800: t

step 35200: train loss 1.4917, val loss 1.4944
step 35300: train loss 1.4827, val loss 1.4918
step 35400: train loss 1.4950, val loss 1.4655
step 35500: train loss 1.4860, val loss 1.4737
step 35600: train loss 1.4801, val loss 1.4668
step 35700: train loss 1.4758, val loss 1.4727
step 35800: train loss 1.4562, val loss 1.4293
step 35900: train loss 1.5195, val loss 1.4917
step 36000: train loss 1.4879, val loss 1.4844
step 36100: train loss 1.4982, val loss 1.4572
step 36200: train loss 1.5127, val loss 1.4562
step 36300: train loss 1.4878, val loss 1.4958
step 36400: train loss 1.4697, val loss 1.4439
step 36500: train loss 1.4905, val loss 1.4861
step 36600: train loss 1.4797, val loss 1.4528
step 36700: train loss 1.4618, val loss 1.4527
step 36800: train loss 1.4642, val loss 1.4545
step 36900: train loss 1.4959, val loss 1.4356
step 37000: train loss 1.4851, val loss 1.4578
step 37100: train loss 1.4921, val loss 1.4706
step 37200: train loss 1.4511, val loss 1.4647
step 37300: t

step 52700: train loss 1.4140, val loss 1.3730
step 52800: train loss 1.3775, val loss 1.3767
step 52900: train loss 1.3935, val loss 1.3712
step 53000: train loss 1.4031, val loss 1.4072
step 53100: train loss 1.4145, val loss 1.3822
step 53200: train loss 1.4206, val loss 1.3739
step 53300: train loss 1.3951, val loss 1.3964
step 53400: train loss 1.3764, val loss 1.3984
step 53500: train loss 1.4018, val loss 1.3760
step 53600: train loss 1.4078, val loss 1.3934
step 53700: train loss 1.3682, val loss 1.3838
step 53800: train loss 1.4036, val loss 1.4026
step 53900: train loss 1.3978, val loss 1.3603
step 54000: train loss 1.4080, val loss 1.4142
step 54100: train loss 1.3972, val loss 1.3773
step 54200: train loss 1.3747, val loss 1.3660
step 54300: train loss 1.3968, val loss 1.3791
step 54400: train loss 1.4102, val loss 1.3783
step 54500: train loss 1.3666, val loss 1.3957
step 54600: train loss 1.4094, val loss 1.3876
step 54700: train loss 1.3869, val loss 1.3973
step 54800: t

step 70200: train loss 1.3417, val loss 1.3492
step 70300: train loss 1.3585, val loss 1.3385
step 70400: train loss 1.3626, val loss 1.3206
step 70500: train loss 1.3507, val loss 1.3283
step 70600: train loss 1.3314, val loss 1.3633
step 70700: train loss 1.3437, val loss 1.3665
step 70800: train loss 1.3295, val loss 1.3222
step 70900: train loss 1.3575, val loss 1.3439
step 71000: train loss 1.3336, val loss 1.3411
step 71100: train loss 1.3314, val loss 1.3451
step 71200: train loss 1.3427, val loss 1.3478
step 71300: train loss 1.3272, val loss 1.3262
step 71400: train loss 1.3111, val loss 1.3102
step 71500: train loss 1.3113, val loss 1.3374
step 71600: train loss 1.3494, val loss 1.3708
step 71700: train loss 1.3314, val loss 1.3456
step 71800: train loss 1.3626, val loss 1.3641
step 71900: train loss 1.3354, val loss 1.3300
step 72000: train loss 1.3831, val loss 1.3381
step 72100: train loss 1.3835, val loss 1.3396
step 72200: train loss 1.3537, val loss 1.3242
step 72300: t

step 87700: train loss 1.3089, val loss 1.3174
step 87800: train loss 1.3417, val loss 1.3133
step 87900: train loss 1.3250, val loss 1.3049
step 88000: train loss 1.3105, val loss 1.3031
step 88100: train loss 1.3516, val loss 1.2725
step 88200: train loss 1.3306, val loss 1.2923
step 88300: train loss 1.2735, val loss 1.3192
step 88400: train loss 1.2832, val loss 1.3081
step 88500: train loss 1.3173, val loss 1.2815
step 88600: train loss 1.3012, val loss 1.2878
step 88700: train loss 1.3043, val loss 1.3041
step 88800: train loss 1.3266, val loss 1.3233
step 88900: train loss 1.2769, val loss 1.2914
step 89000: train loss 1.3344, val loss 1.3040
step 89100: train loss 1.3504, val loss 1.3213
step 89200: train loss 1.3052, val loss 1.2986
step 89300: train loss 1.3167, val loss 1.2667
step 89400: train loss 1.3257, val loss 1.3174
step 89500: train loss 1.3346, val loss 1.3151
step 89600: train loss 1.3012, val loss 1.2846
step 89700: train loss 1.3088, val loss 1.2993
step 89800: t

In [6]:
path = "C:\\Users\\ncbir\\Desktop\\ms.pt"
torch.save(m.state_dict(), path)